#!/usr/bin/env bash

set -e

case "$1" in
configure)

chmod 755 /usr/local/bin/debup 2>/dev/null || true

if [ ! -d /etc/debup ]; then
mkdir -p /etc/debup
fi

if [ ! -f /etc/debup/sources.list ];then
touch /etc/debup/sources.list
chmod 644 /etc/debup/sources.list
fi

TARGET="debup|Ruraam/debup"
if ! grep -qxF "$TARGET" /etc/debup/sources.list; then
echo "$TARGET" >> /etc/debup/sources.list
fi
;;

abort-upgrade|abort-remove|abort-deconfigure)
;;

*)
echo "postinst called with invalid argument $1" >&2
exit 1
;;
esac

exit 0